const KEY = '92c448d7f54a4ad088ddf9883d74c1dc';
const BASE_URL = 'https://prompts34.com';

const urls = [
  BASE_URL,
  // Tool hubs
  `${BASE_URL}/araclar`,
  `${BASE_URL}/araclar/chatgpt-promptlari`,
  `${BASE_URL}/araclar/gemini-promptlari`,
  `${BASE_URL}/araclar/claude-promptlari`,
  `${BASE_URL}/araclar/copilot-promptlari`,
  // Discovery pages
  `${BASE_URL}/en-yeni-prompts`,
  `${BASE_URL}/one-cikanlar`,
  `${BASE_URL}/ucretsiz-promptlar`,
  `${BASE_URL}/prompts`,
  // Categories hub + all category pages
  `${BASE_URL}/kategori`,
  `${BASE_URL}/kategori/cv-hazirlama`,
  `${BASE_URL}/kategori/motivasyon-mektubu`,
  `${BASE_URL}/kategori/mulakat-hazirligi`,
  `${BASE_URL}/kategori/gorsel-olusturma`,
  `${BASE_URL}/kategori/logo-olusturma`,
  `${BASE_URL}/kategori/oyun`,
  `${BASE_URL}/kategori/pazarlama-ve-icerik`,
  `${BASE_URL}/kategori/sanat-ve-yaraticilik`,
  `${BASE_URL}/kategori/portre-ve-fotograf`,
  `${BASE_URL}/kategori/is-stratejisi`,
  `${BASE_URL}/kategori/yazilim-gelistirme`,
  `${BASE_URL}/kategori/midjourney-gorsel`,
  `${BASE_URL}/kategori/kariyer-gelisim`,
  `${BASE_URL}/kategori/egitim`,
  `${BASE_URL}/kategori/sosyal-medya`,
  `${BASE_URL}/kategori/e-ticaret`,
  `${BASE_URL}/kategori/uretkenlik`,
  `${BASE_URL}/kategori/e-posta`,
  // Sözlük (glossary)
  `${BASE_URL}/sozluk`,
  `${BASE_URL}/sozluk/prompt-nedir`,
  `${BASE_URL}/sozluk/prompt-muhendisligi`,
  `${BASE_URL}/sozluk/few-shot-prompting`,
  `${BASE_URL}/sozluk/zero-shot-prompting`,
  `${BASE_URL}/sozluk/sistem-promptu`,
  `${BASE_URL}/sozluk/rol-promptu`,
  `${BASE_URL}/sozluk/chain-of-thought`,
  `${BASE_URL}/sozluk/rag`,
  `${BASE_URL}/sozluk/token`,
  `${BASE_URL}/sozluk/halusinasyon`,
  `${BASE_URL}/sozluk/jailbreak`,
  `${BASE_URL}/sozluk/temperature`,
  `${BASE_URL}/sozluk/top-p`,
  `${BASE_URL}/sozluk/embedding`,
  `${BASE_URL}/sozluk/fine-tuning`,
  // Rehber (guides)
  `${BASE_URL}/rehber`,
  `${BASE_URL}/rehber/iyi-prompt-nasil-yazilir`,
  `${BASE_URL}/rehber/chatgpt-prompt-rehberi`,
  `${BASE_URL}/rehber/gemini-prompt-rehberi`,
  `${BASE_URL}/rehber/midjourney-prompt-rehberi`,
  `${BASE_URL}/rehber/prompt-muhendisligi`,
  // Meslek (professions)
  `${BASE_URL}/meslek`,
  `${BASE_URL}/meslek/yazilimci`,
  `${BASE_URL}/meslek/pazarlamaci`,
  `${BASE_URL}/meslek/icerik-uretici`,
  `${BASE_URL}/meslek/ogretmen`,
  `${BASE_URL}/meslek/ogrenci`,
  `${BASE_URL}/meslek/satisci`,
  `${BASE_URL}/meslek/freelancer`,
  `${BASE_URL}/meslek/girisimci`,
  `${BASE_URL}/meslek/tasarimci`,
  `${BASE_URL}/meslek/ik-uzmani`,
  `${BASE_URL}/meslek/yonetici`,
  `${BASE_URL}/meslek/avukat`,
  `${BASE_URL}/meslek/doktor`,
  `${BASE_URL}/meslek/muhasebeci`,
  `${BASE_URL}/meslek/gazeteci`,
  `${BASE_URL}/meslek/arastirmaci`,
  `${BASE_URL}/meslek/cevirmen`,
  `${BASE_URL}/meslek/mimari`,
  `${BASE_URL}/meslek/emlakci`,
  `${BASE_URL}/meslek/eticaret-satici`,
  // Kullanım (use cases)
  `${BASE_URL}/kullanim`,
  `${BASE_URL}/kullanim/email-yazma`,
  `${BASE_URL}/kullanim/instagram-icerigi`,
  `${BASE_URL}/kullanim/linkedin-gonderisi`,
  `${BASE_URL}/kullanim/urun-aciklamasi`,
  `${BASE_URL}/kullanim/blog-yazisi`,
  `${BASE_URL}/kullanim/sunum-hazirlama`,
  `${BASE_URL}/kullanim/ders-plani`,
  `${BASE_URL}/kullanim/ozet-cikarma`,
  `${BASE_URL}/kullanim/ceviri`,
  `${BASE_URL}/kullanim/kod-aciklama`,
  `${BASE_URL}/kullanim/sql-sorgusu`,
  `${BASE_URL}/kullanim/regex`,
  `${BASE_URL}/kullanim/ilan-metni`,
  `${BASE_URL}/kullanim/mulakat-sorulari`,
  `${BASE_URL}/kullanim/sosyal-medya-kampanyasi`,
  `${BASE_URL}/kullanim/reklam-metni`,
  `${BASE_URL}/kullanim/soguk-email`,
  `${BASE_URL}/kullanim/musteri-yorumu-cevabi`,
  `${BASE_URL}/kullanim/beyin-firtinasi`,
  `${BASE_URL}/kullanim/gorsel-prompt`,
  `${BASE_URL}/kullanim/logo-fikri`,
  `${BASE_URL}/kullanim/arastirma-ozet`,
  `${BASE_URL}/kullanim/is-plani`,
  `${BASE_URL}/kullanim/ozgecmis-yazma`,
  `${BASE_URL}/kullanim/youtube-senaryosu`,
];

const res = await fetch('https://api.indexnow.org/indexnow', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json; charset=utf-8' },
  body: JSON.stringify({
    host: 'prompts34.com',
    key: KEY,
    keyLocation: `${BASE_URL}/${KEY}.txt`,
    urlList: urls,
  }),
});

console.log(`IndexNow: ${res.status} ${res.statusText}`);
console.log(`Submitted ${urls.length} URLs`);
